development:
  adapter: postgresql
  database: publicart_development
  encoding: unicode
  port: 15432
  host: localhost
  min_messages: warning

test:
  adapter: postgresql
  database: publicart_test
  encoding: unicode
  port: 15432
  host: localhost
  min_messages: warning